from django import template
from django.db.models.fields.files import ImageFieldFile

register = template.Library()


def to_bool(val):
    if isinstance(val, str):
        return val.strip().lower() == "true"
    return bool(val)


@register.filter
def get_fields(model,
               args=None):
    """
    Возвращает все поля модели.
    Не возвращает наборы данных для внешних ключей.

    Можно исключить поля в модели и/или игнорировать автогенерированные поля.

    Применяется совместно с шаблонами general/detail.html, general/primitive_list.html.


    Применение в шаблоне:

    1) Показать все поля в модели (не обращать внимание на EXCLUDE_FROM_GET_FIELDS в модели,
    и отобразить автогенерированные поля):
    {{ object|get_fields }}

    2) Игнорировать автогенерированные поля:
    {{ object|get_fields:"True" }}

    3) Игнорировать факт исключения полей в модели:
    {{ object|get_fields:"False,True" }}


    Подготовка модели, если надо игнорировать поля:

    class Product(models.Model):
        EXCLUDE_FROM_GET_FIELDS = ['price', ]



    """

    ignore_exclude_from_get_fields = False
    ignore_autogenerated_fields = False

    if args:

        args = args.replace(' ', '').lower()

        if not (args == "true" or args == "false" or args == 'true,false' or args == 'true,true' or args == "false,true"):
            raise ValueError(f"The filter can accept only \"True\", \"False\", \"True,False\", \"False,True\", \"True,True\". {args} was given.")

        parts = args.split(',')
        if len(parts) == 1:
            ignore_autogenerated_fields = to_bool(parts[0].strip())
        elif len(parts) == 2:
            ignore_autogenerated_fields = to_bool(parts[0].strip())
            ignore_exclude_from_get_fields = to_bool(parts[1].strip())


    # Получаем список полей для исключения из модели (атрибут EXCLUDE_FROM_GET_FIELDS)
    if ignore_exclude_from_get_fields:
        EXCLUDE_FIELDS = []
    else:
        EXCLUDE_FIELDS = getattr(model.__class__, 'EXCLUDE_FROM_GET_FIELDS', [])

    fields = []

    for field in model._meta.get_fields():
        # Исключить наборы данных.
        if field.one_to_many or field.many_to_many:
            continue

        # Учесть автогенерированные поля
        if ignore_autogenerated_fields and field.auto_created:
            continue

        # Учесть исключенные поля.
        if field.name in EXCLUDE_FIELDS:
            continue

        value = getattr(model, field.name)
        fields.append({
            'label': field.verbose_name,
            'name': field.name,
            'value': value,
            'is_image': isinstance(value, ImageFieldFile),
        })
    return fields
