"""
Django settings for master_pol project.

Generated by Cookiecutter using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os

from django.urls import reverse_lazy  # PREP
from . import secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wq_x*w%6zxwi@ux#(gmfq*ije&jy-g*p7(0z@)fy2yef9@b1c%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'crook-unfrosted-proponent.ngrok-free.dev', '0.0.0.0', '10.8.0.1',]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    # PREP {
    "django_admin_rest_api",
    "django_admin_react",
    "rest_framework",
    # } PREP
    
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # PREP {
    "django_model_info.apps.DjangoModelInfoConfig",
    "jquery",
    "django_bootstrap_icons",

    "home",
    "general",
    "accounts",
    # } PREP

    # STUD! {
    "product_list",
    # } STUD!

    # { Требуется для allauth
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # } Требуется для allauth


    # PREP {
    # Должно быть крайним в списке. См. https://pypi.org/project/django-cleanup/
    "django_cleanup.apps.CleanupConfig",
    # } PREP
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware", # PREP
    "django.middleware.common.CommonMiddleware",
    "accounts.middleware.SocialLoginBaseRedirectMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # { Требуется для allauth
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # } Требуется для allauth
]

ROOT_URLCONF = "master_pol.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",  # PREP
                "general.context_processors.project_context",  # PREP
            ],
        },
    },
]

WSGI_APPLICATION = "master_pol.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PREP {

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# } PREP

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# PREP {
LANGUAGE_CODE = "ru"

LANGUAGES = [
    ("ru", _("Russian")),
]

TIME_ZONE = (
    "Europe/Moscow"  # PREP https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
)
# } PREP

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# PREP {

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

PASSWORD_HASHERS = [
    "plaintext_password.PlaintextPasswordHasher",
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = reverse_lazy("login")


AUTH_USER_MODEL = 'accounts.User'


BS_ICONS_BASE_PATH = os.path.join(BASE_DIR, "general/static/general/img/bootstrap-icons")

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ]
}

# } PREP


# Требуется для allauth {
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': secret.SOCIALACCOUNT_CLIENT_ID,
            'secret': secret.SOCIALACCOUNT_SECRET,
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',  # Или 'offline', если нужен refresh_token
        }
    }
}

CSRF_TRUSTED_ORIGINS = ["https://crook-unfrosted-proponent.ngrok-free.dev",]

# ngrok принимает TLS и пересылает запросы в Django по HTTP с заголовком
# X-Forwarded-Proto: https. Без этой настройки Django считает схему http,
# и allauth отдаёт Google redirect_uri http://... вместо зарегистрированного
# https://... (redirect_uri_mismatch).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Единственный origin, зарегистрированный как Authorized redirect URI в
# Google Cloud Console. На нём должна выполняться авторизация Google:
# accounts.middleware.SocialLoginBaseRedirectMiddleware перенаправляет
# сюда любой другой host при входе через Google.
SOCIALACCOUNT_BASE_URL = "https://crook-unfrosted-proponent.ngrok-free.dev"

# } Требуется для allauth
