# Generated by Django 5.2 on 2026-10-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
